# Generated by Django 5.0.2 on 2024-02-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('IdMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('IdEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('porcentaje', models.IntegerField()),
                ('temas', models.CharField(max_length=150)),
                ('IdMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.materia')),
            ],
        ),
        migrations.CreateModel(
            name='PactoPedagogico',
            fields=[
                ('IdPactoPedagogico', models.AutoField(primary_key=True, serialize=False)),
                ('IdMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.materia')),
            ],
        ),
    ]
