# Generated by Django 5.0.2 on 2024-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
