# Generated by Django 5.0.2 on 2024-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_evaluacion_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
