# Generated by Django 5.0.2 on 2024-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_evaluacion_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
